import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Hedaer from "./layouts/Header";
import RootContextProvider from "./store";
import Bg from "./assets/bg.svg";

import clsx from "clsx";
import SolanaWalletContextProvider from "./store/Solnan";
import ThemeMatProvider from "./providers/ThemeMatProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeMatProvider>
        <SolanaWalletContextProvider>
          <RootContextProvider>
            <body
              className={clsx(inter.className, " h-screen w-screen ")}
              style={{
                backgroundImage: `url(${Bg.src})`,
                backgroundSize: `100% 100%`,
              }}
            >
              <Hedaer />

              <div className="flex w-full">{children}</div>
            </body>
          </RootContextProvider>
        </SolanaWalletContextProvider>
      </ThemeMatProvider>
    </html>
  );
}
